version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: agentflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nats:
    image: nats:2.10-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js", "-m", "8222"]
    volumes:
      - nats_data:/data

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./scripts/clickhouse_schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      CLICKHOUSE_DB: agentflow
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""

  agentflow-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/agentflow?sslmode=disable
      REDIS_URL: redis://redis:6379
      NATS_URL: nats://nats:4222
      CLICKHOUSE_URL: http://clickhouse:8123
    depends_on:
      - postgres
      - redis
      - nats
      - clickhouse
    volumes:
      - ./examples:/app/examples

volumes:
  postgres_data:
  redis_data:
  nats_data:
  clickhouse_data: