# golangci-lint configuration for v2.x
# Note: This version has a restrictive schema that doesn't allow many common configuration options
# See: https://golangci-lint.run/docs/product/migration-guide

version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - bodyclose
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  
  disable:
    - depguard
    - dogsled