apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: agentflow
data:
  nats.conf: |
    port: 4222
    http_port: 8222
    
    jetstream {
      store_dir: /data
      max_memory_store: 1GB
      max_file_store: 10GB
    }
    
    cluster {
      name: agentflow
      port: 6222
    }

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-pvc
  namespace: agentflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: agentflow
  labels:
    app: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: nats:2.10-alpine
        command:
        - nats-server
        - --config
        - /etc/nats/nats.conf
        ports:
        - containerPort: 4222
        - containerPort: 8222
        - containerPort: 6222
        volumeMounts:
        - name: nats-storage
          mountPath: /data
        - name: nats-config
          mountPath: /etc/nats/nats.conf
          subPath: nats.conf
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8222
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8222
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: nats-storage
        persistentVolumeClaim:
          claimName: nats-pvc
      - name: nats-config
        configMap:
          name: nats-config

---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: agentflow
  labels:
    app: nats
spec:
  ports:
  - name: client
    port: 4222
    targetPort: 4222
  - name: http
    port: 8222
    targetPort: 8222
  - name: cluster
    port: 6222
    targetPort: 6222
  selector:
    app: nats