apiVersion: apps/v1
kind: Deployment
metadata:
  name: workers
  namespace: agentflow
  labels:
    app: workers
    component: agentflow
spec:
  replicas: 5
  selector:
    matchLabels:
      app: workers
  template:
    metadata:
      labels:
        app: workers
        component: agentflow
    spec:
      containers:
      - name: worker
        image: ghcr.io/siddhant-k-code/agentflow-infrastructure/agentflow-worker:latest
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: clickhouse-secret
              key: password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        - name: WORKER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DB_HOST
          value: postgres
        - name: CLICKHOUSE_HOST
          value: clickhouse
        - name: REDIS_HOST
          value: redis
        - name: NATS_URL
          value: nats://nats:4222
        volumeMounts:
        - name: config
          mountPath: /app/configs/config.yaml
          subPath: config.yaml
        - name: tmp
          mountPath: /app/tmp
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
      volumes:
      - name: config
        configMap:
          name: agentflow-config
      - name: tmp
        emptyDir: {}

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: workers-hpa
  namespace: agentflow
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: workers
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60