apiVersion: v1
kind: Namespace
metadata:
  name: agentflow
  labels:
    name: agentflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: agentflow
  labels:
    app: orchestrator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
      - name: orchestrator
        image: agentflow/orchestrator:latest
        ports:
        - containerPort: 8080
        env:
        - name: NATS_URL
          value: "nats://nats:4222"
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: agentflow-secrets
              key: postgres-url
        - name: CLICKHOUSE_URL
          value: "tcp://clickhouse:9000"
        - name: TRACING_URL
          value: "http://jaeger:14268/api/traces"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: agentflow
spec:
  selector:
    app: orchestrator
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runtime
  namespace: agentflow
  labels:
    app: runtime
spec:
  replicas: 3
  selector:
    matchLabels:
      app: runtime
  template:
    metadata:
      labels:
        app: runtime
    spec:
      containers:
      - name: runtime
        image: agentflow/runtime:latest
        ports:
        - containerPort: 8081
        env:
        - name: NATS_URL
          value: "nats://nats:4222"
        - name: ORCHESTRATOR_URL
          value: "http://orchestrator:8080"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: runtime
  namespace: agentflow
spec:
  selector:
    app: runtime
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-router
  namespace: agentflow
  labels:
    app: llm-router
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llm-router
  template:
    metadata:
      labels:
        app: llm-router
    spec:
      containers:
      - name: llm-router
        image: agentflow/llm-router:latest
        ports:
        - containerPort: 8082
        env:
        - name: NATS_URL
          value: "nats://nats:4222"
        - name: PROVIDERS_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: agentflow-secrets
              key: openai-api-key
        - name: PROVIDERS_ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: agentflow-secrets
              key: anthropic-api-key
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: llm-router
  namespace: agentflow
spec:
  selector:
    app: llm-router
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: ClusterIP